apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: PLACEHOLDER_IMAGE   # will be replaced by CI to the pushed image
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/testdb"
        ports:
        - containerPort: 8080
