apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-container
          image: us-central1-docker.pkg.dev/sirisha-test1/mongo-repo/mongo-gke-demo:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-service:27017/testdb"
