name: CI/CD - Deploy Mongo App to GKE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GCP_PROJECT: ${{ vars.GCP_PROJECT }}
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}         # Example: gke-demo-cluster
  GKE_ZONE: ${{ vars.GKE_ZONE }}               # Example: us-central1-a
  ARTIFACT_REGISTRY_LOCATION: ${{ vars.ARTIFACT_REGISTRY_LOCATION }}
  ARTIFACT_REGISTRY_REPOSITORY: ${{ vars.ARTIFACT_REGISTRY_REPOSITORY }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy to GKE

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Setup Google Cloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}

      # Step 4: Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Step 5: Build and Push Docker image to Artifact Registry
      - name: Build and Push Docker image to Artifact Registry
        run: |
          IMAGE_URI=${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          echo "Building image: $IMAGE_URI"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Step 6: Get GKE credentials
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
            --zone ${{ env.GKE_ZONE }} \
            --project ${{ env.GCP_PROJECT }}

      # Step 7: Install GKE Auth Plugin (fix for kubectl authentication)
      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      # Step 8: Deploy Mongo and App to GKE
      - name: Deploy Mongo and App to GKE
        run: |
          kubectl apply -f k8s/mongo-deployment.yaml
          kubectl apply -f k8s/mongo-service.yaml
          kubectl apply -f k8s/app-deployment.yaml
          kubectl apply -f k8s/app-service.yaml

      # Step 9: Verify Deployment Rollouts
      - name: Verify deployment rollout
        run: |
          kubectl rollout status deployment/mongo-deployment
          kubectl rollout status deployment/app-deployment

      # Step 10: Get Service Info
      - name: Get service info
        run: kubectl get svc -o wide
